In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.Collecting numpy
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 640.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 650.2 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 324.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 991.0 kB/s eta 0:00:13
   ---------------------------------------- 0.1/12.6 MB 1.3 MB/s eta 0:00:10
   ---------------------------------------- 0.1/12.6 MB 1.2 MB/s eta 0:00:11
    --------------------------------------- 0.2/12.6 MB 1.1 MB/s eta 0:00:12
    --------------------------------------- 0.3/12.6 MB 1.2 MB/s eta 0:00:11
    --------------------------------------- 0.3/12.6 MB 1.2 MB/s eta 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: c:\Python312\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
Z = np.matrix([[1, 0], [0, -1]])
X = np.matrix([[0, 1], [1, 0]])

In [4]:
state = np.matrix([[1], [0], [0], [0]])

In [7]:
stab = np.kron(Z,Z)

In [8]:
np.dot(stab, state)

matrix([[1],
        [0],
        [0],
        [0]])

In [11]:
neg_Z = -1 * Z

In [12]:
error_stab = np.kron(neg_Z, Z)

In [13]:
np.dot(error_stab, state)

matrix([[-1],
        [ 0],
        [ 0],
        [ 0]])

In [14]:
another_state = np.matrix([[0], [1], [0], [0]])

# 01 --> Z-Z


In [15]:
stab = np.kron(Z, neg_Z)

In [16]:
np.dot(stab, another_state)

matrix([[0],
        [1],
        [0],
        [0]])

In [17]:
stab_2 = np.kron(Z,Z)

In [18]:
np.dot(stab_2, another_state)

matrix([[ 0],
        [-1],
        [ 0],
        [ 0]])

In [19]:
np.dot(another_state.T, stab_2)

matrix([[ 0, -1,  0,  0]])

In [20]:
def expval(state, stab):
    return np.dot(np.dot(state.T, stab), state)

In [22]:
expval(another_state, np.kron(Z,Z)), expval(another_state, np.kron(-Z,Z))

(matrix([[-1]]), matrix([[1]]))